import { dir } from 'i18next';

import '@/app/css/globals.css';
import { bodoniMT, bodoniModa, calibri, solway } from '@/assets/fonts';
import { languages } from '../i18n/settings';
import { Toaster } from '@/components/ui/toaster';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

// export async function generateMetadata({ params: { lng } }: {
//   params: {
//     lng: string;
//   };
// }) {
//   if (languages.indexOf(lng) < 0) lng = fallbackLng
//   // eslint-disable-next-line react-hooks/rules-of-hooks
//   const { t } = await useTranslation(lng)
//   return {
//     title: t('title'),
//     content: 'A playground to explore new Next.js 13/14 app directory features such as nested layouts, instant loading states, streaming, and component level data fetching.'
//   }
// }

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: {
    lng: any;
  };
}) {
  return (
    <html
      lang={lng}
      dir={dir(lng)}
      className={`${bodoniModa.variable} ${bodoniMT.variable} ${calibri.variable} ${solway.variable} scroll-smooth`}
    >
      <body className={`font-calibri text-black antialiased`}>
        <div className='min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip'>
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
